### ISSUE TITLE
Twitter sign-in error using omniAuth

### ISSUE THREAD

**Issue by vigneshrams** [upvote/upvote#34]
HI,

I set up Twitter Secret Key and Secret Password in environments/developement.rb file as,

ENV['TWITTER_API_KEY'] = "123456789";
  ENV['TWITTER_API_SECRET'] = "abcdefghijklmn";

But when I try to login, It gives me error like the following, 

> NameError at /users/auth/twitter/callback
> undefined local variable or method `auth' for #<Class:0x007f9c28101f28>**

Error shows in this line of code 

> email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com"

Please help me get over it.

**Comment by chrisb** [comment]
Hey @vigneshrams! I don't have too much time at the moment to test it, but I just pushed a fix to master that I think will solve the issue: https://github.com/upvote/upvote/commit/3eec20ff8a21341f455d82221db9c2d26cb1c4ed

Mind testing it for me and seeing if it works for you? Hope it does!

**Comment by vigneshrams** [comment]
Hey @chrisb Thanks for quick reply. I tested your fix but it did not solve the issue. I got the below error now 

> undefined method `info' for nil:NilClass

From this method,
`def self.email_or_temp_from_auth(auth)
    auth.info.email ? auth.info.email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com"
  end`

Please Help me on this.

**Comment by chrisb** [comment]
How about this one? https://github.com/upvote/upvote/commit/61058e71c263705214334983f122d383cc8f7c1c

**Comment by vigneshrams** [comment]
I have made little correction to your Fix. Please review and accept the pull request. Thanks

Don't we store user email from Twitter and FB sign-up process ?
